
import * as d from './components';

export const DIRECTIVES = [
  d.CpyAccordion,
  d.CpyAlert,
  d.CpyAvatar,
  d.CpyBadge,
  d.CpyButton,
  d.CpyCard,
  d.CpyCarousel,
  d.CpyCodeBlock,
  d.CpyCodeSnippet,
  d.CpyContentsList,
  d.CpyContentsListItem,
  d.CpyContextMenu,
  d.CpyContextMenuItem,
  d.CpyContextMenuTrigger,
  d.CpyDialog,
  d.CpyDrawer,
  d.CpyDrawerContainer,
  d.CpyExpandCollapse,
  d.CpyIcon,
  d.CpyInput,
  d.CpyInputToggle,
  d.CpyLink,
  d.CpyNavMenu,
  d.CpyNavMenuItem,
  d.CpyPageContent,
  d.CpyPopup,
  d.CpySpinner,
  d.CpyStack,
  d.CpyTable,
  d.CpyToast,
  d.CpyToolbar,
  d.CpyTooltip
];
